using src.Models.Offenses;

namespace src.Seeders
{
    public static class OffenseDatabaseSeeder
    {
        public static void Seed(OffenseDbContext context)
        {
            context.Database.EnsureDeleted(); // deletes existing database
            context.Database.EnsureCreated(); // recreates database

            var records = new JsonOffenseRecord[]
            {
                new () {
                    Weiserzeichen = "7",
                    Fallnummer = "00001",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "TK123456",
                    Krankenversicherung = "TechnikerKrankenkasse",
                    Versicherungsnummer = "VN123456",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "1",
                    Titel = "Dr.",
                    Geburtsdatum = new DateTime(1990, 1, 1),
                    Vorname = "Klaus",
                    Nachname = "Müller",
                    Geburtsname = "Müller",
                    Str = "Berliner Straße",
                    Hausnummer = "123a",
                    Plz = "80335",
                    Wohnort = "München",
                    Ortsteil = "Maxvorstadt",
                    Geburtsort = "Stuttgart",
                    Aufforderungsdatum = new DateTime(2023, 1, 1),
                    BeginnRueckstand = new DateTime(2022, 12, 1),
                    VerzugBis = new DateTime(2023, 3, 1),
                    Verzugsende = new DateTime(2023, 4, 1),
                    Beitragsrueckstand = "150,00",
                    Sollbeitrag = "180,50",
                    Folgemeldung = 1,
                    Bemerkungen = "Erste Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 1, 15)
                },
                new () {
                    Weiserzeichen = "9",
                    Fallnummer = "00003",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "DA345678",
                    Krankenversicherung = "DAK-Gesundheit",
                    Versicherungsnummer = "VN345678",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "1",
                    Titel = "",
                    Geburtsdatum = new DateTime(1978, 3, 22),
                    Vorname = "Thomas",
                    Nachname = "Wagner",
                    Geburtsname = "Wagner",
                    Str = "Schillerstraße",
                    Hausnummer = "78",
                    Plz = "60313",
                    Wohnort = "Frankfurt",
                    Ortsteil = "Innenstadt",
                    Geburtsort = "Mainz",
                    Aufforderungsdatum = new DateTime(2023, 3, 1),
                    BeginnRueckstand = new DateTime(2023, 2, 1),
                    VerzugBis = new DateTime(2023, 5, 1),
                    Verzugsende = new DateTime(2023, 6, 1),
                    Beitragsrueckstand = "175,50",
                    Sollbeitrag = "195,00",
                    Folgemeldung = 1,
                    Bemerkungen = "Dritte Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 3, 15)
                },
                new () {
                    Weiserzeichen = "10",
                    Fallnummer = "00004",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "AO901234",
                    Krankenversicherung = "AOK Bayern",
                    Versicherungsnummer = "VN901234",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "2",
                    Titel = "Dr.",
                    Geburtsdatum = new DateTime(1992, 7, 19),
                    Vorname = "Maria",
                    Nachname = "Becker",
                    Geburtsname = "Fischer",
                    Str = "Goethestraße",
                    Hausnummer = "12",
                    Plz = "70173",
                    Wohnort = "Stuttgart",
                    Ortsteil = "Mitte",
                    Geburtsort = "Heidelberg",
                    Aufforderungsdatum = new DateTime(2023, 4, 1),
                    BeginnRueckstand = new DateTime(2023, 3, 1),
                    VerzugBis = new DateTime(2023, 6, 1),
                    Verzugsende = new DateTime(2023, 7, 1),
                    Beitragsrueckstand = "280,00",
                    Sollbeitrag = "310,25",
                    Folgemeldung = 1,
                    Bemerkungen = "Vierte Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 4, 15)
                },
                new () {
                    Weiserzeichen = "11",
                    Fallnummer = "00005",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "KK567890",
                    Krankenversicherung = "KKH",
                    Versicherungsnummer = "VN567890",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "1",
                    Titel = "",
                    Geburtsdatum = new DateTime(1980, 12, 2),
                    Vorname = "Michael",
                    Nachname = "Hoffmann",
                    Geburtsname = "Hoffmann",
                    Str = "Bahnhofstraße",
                    Hausnummer = "34c",
                    Plz = "50667",
                    Wohnort = "Köln",
                    Ortsteil = "Altstadt",
                    Geburtsort = "Bonn",
                    Aufforderungsdatum = new DateTime(2023, 5, 1),
                    BeginnRueckstand = new DateTime(2023, 4, 1),
                    VerzugBis = new DateTime(2023, 7, 1),
                    Verzugsende = new DateTime(2023, 8, 1),
                    Beitragsrueckstand = "195,75",
                    Sollbeitrag = "225,50",
                    Folgemeldung = 1,
                    Bemerkungen = "Fünfte Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 5, 15)
                },
                new () {
                    Weiserzeichen = "12",
                    Fallnummer = "00006",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "BA234567",
                    Krankenversicherung = "Barmer",
                    Versicherungsnummer = "VN234567",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "2",
                    Titel = "Prof.",
                    Geburtsdatum = new DateTime(1987, 11, 5),
                    Vorname = "Anna",
                    Nachname = "Koch",
                    Geburtsname = "Meyer",
                    Str = "Mozartweg",
                    Hausnummer = "67",
                    Plz = "01067",
                    Wohnort = "Dresden",
                    Ortsteil = "Altstadt",
                    Geburtsort = "Leipzig",
                    Aufforderungsdatum = new DateTime(2023, 6, 1),
                    BeginnRueckstand = new DateTime(2023, 5, 1),
                    VerzugBis = new DateTime(2023, 8, 1),
                    Verzugsende = new DateTime(2023, 9, 1),
                    Beitragsrueckstand = "165,25",
                    Sollbeitrag = "185,00",
                    Folgemeldung = 1,
                    Bemerkungen = "Sechste Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 6, 15)
                },
                new () {
                    Weiserzeichen = "13",
                    Fallnummer = "00007",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "IK678901",
                    Krankenversicherung = "IKK classic",
                    Versicherungsnummer = "VN678901",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "1",
                    Titel = "",
                    Geburtsdatum = new DateTime(1995, 4, 8),
                    Vorname = "Stefan",
                    Nachname = "Schäfer",
                    Geburtsname = "Schäfer",
                    Str = "Lindenallee",
                    Hausnummer = "89d",
                    Plz = "04109",
                    Wohnort = "Leipzig",
                    Ortsteil = "Zentrum",
                    Geburtsort = "Chemnitz",
                    Aufforderungsdatum = new DateTime(2023, 7, 1),
                    BeginnRueckstand = new DateTime(2023, 6, 1),
                    VerzugBis = new DateTime(2023, 9, 1),
                    Verzugsende = new DateTime(2023, 10, 1),
                    Beitragsrueckstand = "210,50",
                    Sollbeitrag = "240,75",
                    Folgemeldung = 1,
                    Bemerkungen = "Siebte Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 7, 15)
                },
                new () {
                    Weiserzeichen = "14",
                    Fallnummer = "00008",
                    Meldedatum = new DateTime(2022, 1, 1),
                    Versicherungsunternehmensnummer = "HE890123",
                    Krankenversicherung = "hkk",
                    Versicherungsnummer = "VN890123",
                    BeginnVersicherung = new DateTime(2021, 1, 1),
                    Geschlecht = "2",
                    Titel = "Dr.",
                    Geburtsdatum = new DateTime(1983, 9, 30),
                    Vorname = "Julia",
                    Nachname = "Wolf",
                    Geburtsname = "Wolf",
                    Str = "Kirchplatz",
                    Hausnummer = "3",
                    Plz = "30159",
                    Wohnort = "Hannover",
                    Ortsteil = "Mitte",
                    Geburtsort = "Braunschweig",
                    Aufforderungsdatum = new DateTime(2023, 8, 1),
                    BeginnRueckstand = new DateTime(2023, 7, 1),
                    VerzugBis = new DateTime(2023, 10, 1),
                    Verzugsende = new DateTime(2023, 11, 1),
                    Beitragsrueckstand = "245,00",
                    Sollbeitrag = "275,25",
                    Folgemeldung = 1,
                    Bemerkungen = "Achte Mahnung",
                    Anhoerungsdatum = new DateTime(2023, 8, 15)
                }
            };

            // split Hausnummer into digits/extra part
            var dtoRecords = records.Select(record =>
            {
                var dto = new DtoOffenseRecord();
                dto.UpdateRecord(record);
                dto.SplitHausnummer();
                return dto;
            }).ToArray();

            // add records to database
            context.OffenseRecords.AddRange(dtoRecords);
            context.SaveChanges();
        }
    }
}
